destinations/urls.py
from django.urls import path

from . import views

app_name = 'destinations'

urlpatterns = [
    path('', views.home, name='home'),
    path('entidades/cadastro/', views.entidades_insert, name='entidade-insert'),  # noqa: E501
    path('entidades/atualizar/', views.entidades_update,
         name='entidade-update'),  # ignore
    path('saidas/', views.saidas, name='saidas'),
    path('saidas/load', views.loadCronograma, name='load-saidas'),
    path('saidas/registrodestino/', views.registrodestino, name='registrodestino'),  # noqa: E501
    path('planilha/', views.planilha, name='planilha'),
]

sipe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('destinations.urls')),
]

destinations/models.py
from django.db import models


class Entidade(models.Model):
    cnpj = models.CharField(max_length=14, null=True)  # type: ignore
    razao = models.CharField(max_length=50)  # type: ignore
    nf = models.CharField(max_length=50, null=True, blank=True)  # type: ignore
    contatos = models.CharField(
        max_length=50, null=True, blank=True)  # type: ignore
    email = models.CharField(max_length=50, null=True,
                             blank=True)  # type: ignore
    fones = models.CharField(
        max_length=35, null=True, blank=True)  # type: ignore
    validade = models.DateField()  # type: ignore
    ativo = models.CharField(max_length=1, default="s")  # type: ignore

    def __str__(self):
        return self.razao


class RegistroLancamentos(models.Model):
    dataRegistro = models.DateField()  # type: ignore
    tipoResgistro = models.CharField(max_length=2)
    respINMEQ = models.CharField(max_length=50)  # type: ignore
    testINMEQ = models.CharField(max_length=50)  # type: ignore
    id_entidade = models.ForeignKey(
        Entidade, on_delete=models.SET_NULL, null=True, default=None
    )  # type: ignore

    def __str__(self):
        return str(self.id)


class Lancamento(models.Model):
    data = models.DateField()  # type: ignore
    tc = models.CharField(max_length=7)
    tipo_saida = models.CharField(max_length=2)  # type: ignore
    produto = models.CharField(max_length=60)  # type: ignore
    marca = models.CharField(max_length=50)  # type: ignore
    qn = models.CharField(max_length=10)  # type: ignore
    unid = models.CharField(max_length=5, default=None)  # type: ignore
    quant = models.SmallIntegerField()  # type: ignore
    quant_doado = models.SmallIntegerField()
    quant_inutilizado = models.SmallIntegerField()
    id_registro = models.ForeignKey(
        RegistroLancamentos, on_delete=models.SET_NULL, null=True, default=True
    )

    def __str__(self):
        return str(self.id)

destinations/forms.py
from django import forms
from django.core.exceptions import ValidationError

from destinations.models import Entidade


class EntidadeForm(forms.ModelForm):
    option = forms.CharField(widget=forms.HiddenInput())
    selectEntidade = forms.CharField(
        label='Entidade',
        widget=forms.Select()
    )

    class Meta:
        model = Entidade
        fields = [
            "cnpj",
            "razao",
            "nf",
            "contatos",
            "email",
            "fones",
            "validade",
            "ativo",
        ]

        labels = {
            'cnpj': 'cnpj',
            "razao": "Razão Social",
            "nf": "Nome de Fantasia",
            "contatos": "Contatos",
            "email": "E-mail",
            "fones": "Telefones",
            "validade": "Validade do cadastro",
            "ativo": "Ativo?",
        }

        # help_texts = {}

        error_messages = {
            "cnpj": {
                "required": "Este campo não pode ficar vazio",
                "invalid": "Digite apenas números",
            },
            "validade": {"required": "Defina uma data para a validade"},
            "contatos": {"required": "Defina pelo menos um contato"},
            "razão": {"required": "Razão Social não pode ser nulo"},
        }

        widgets = {
            "cnpj": forms.TextInput(
                attrs={
                    "placeholder": "Digite apenas números",
                    "maxlength": 14,
                },
            ),
            "razao": forms.TextInput(
                attrs={
                    'placeholder': 'Digite algo com pelo menos 10 caracteres aqui'  # noqa: E501
                }
            ),
            "ativo": forms.RadioSelect(
                choices=[("s", "Sim"), ("n", "Não")],
                attrs={
                    "class": "div-row-left",
                },
            ),
            "validade": forms.DateInput(attrs={"type": "date"}),
        }

    # Validações por campo

    def clean_cnpj(self):
        data = self.cleaned_data["cnpj"]
        nao_numerico = None
        try:
            int(data)
            nao_numerico = False
        except Exception:
            nao_numerico = True

        if nao_numerico:
            raise ValidationError(
                "Digite apenas números",
                code='invalid'
            )

        if len(data) < 14 or nao_numerico:
            raise ValidationError(
                [
                    ValidationError(
                        "O CNPJ não pode ser nulo", code="invalid"
                    ),  # ignore
                    ValidationError(
                        "O CNPJ deve ter 14 dígitos", code="invalid"
                    ),  # ignore
                    ValidationError(
                        'Digite apenas números',
                        code='invalid'
                    )
                ]
            )

        return data

    def clean_razao(self):
        data = self.cleaned_data['razao']

        if len(data) < 10:
            raise ValidationError(
                'Digite algo com pelo menos 10 caracteres',
                code='invalid'
            )

        return data


class CronogramaForm(forms.Form):
    crono = forms.FileField(
        widget=forms.FileInput(attrs={'accept': '.pdf'})
    )

    option = forms.CharField(
        widget=forms.HiddenInput()
    )

    data = forms.DateField()
    tc = forms.CharField()
    produto = forms.CharField()
    marca = forms.CharField()
    qn = forms.CharField()
    quant = forms.CharField()
    opt = [
        ('dt', 'Doação total'),
        ('dp', "Doação parcial"),
        ('rt', 'Retirada'),
        ('in', 'Inutilização')
    ]
    tipo_saida = forms.CharField(
        widget=forms.Select(choices=opt)
    )

destinations/views.py
from django.contrib import messages
from django.shortcuts import render

from utils.destinations import pdfhandler
from utils.destinations.factory import makeSaida

from . import forms, models


def home(request):
    return render(request, "destinations/pages/index.html")


def entidades_insert(request):  # View de rota para cadastro de entidades
    if request.POST:
        POST = request.POST
        request.session["insert_form_entidades"] = POST
        form = forms.EntidadeForm(POST)
        ent = models.Entidade.objects.filter(cnpj=dict(POST)['cnpj'][0])
        if form.is_valid() and not ent:
            form.save(commit=True)
            messages.success(request, "ENTIDADE SALVA COM SUCESSO")
            del request.session["insert_form_entidades"]
            form = forms.EntidadeForm()
        else:
            messages.error(request, "CORRIJA OS ERROS DO FORMULÁRIO ")
    else:
        form = forms.EntidadeForm()

    return render(
        request,
        "destinations/pages/entidades-insert.html",
        context={
            "form": form,
        },
    )


def entidades_update(request):  # View da rota para update de entidades
    form = forms.EntidadeForm()
    options = models.Entidade.objects.filter(ativo='s')
    id_selected = None

    if request.POST:
        POST = request.POST
        request.session["update_form_entidades"] = POST
        option_match = dict(POST)['option'][0]
        id_selected = dict(POST)['selectEntidade'][0]

        match option_match:
            case 'load':
                entidade = models.Entidade.objects.get(pk=id_selected)
                form = forms.EntidadeForm(instance=entidade)

            case 'save':
                if form.is_valid():
                    form.save(commit=True)
                    messages.success(request, "ENTIDADE SALVA COM SUCESSO")
                    del request.session["update_form_entidades"]
                    form = forms.EntidadeForm()
                else:
                    messages.error(request, "CORRIJA OS ERROS DO FORMULÁRIO ")

    return render(
        request,
        "destinations/pages/entidades-update.html",
        context={
            "form": form,
            'options': options,
            'id_selected': id_selected
        },
    )


def loadCronograma(request):
    form = forms.CronogramaForm()
    data = None
    print_data = False
    if request.POST:
        POST = request.POST
        request.session['load_cronograma_pdf'] = POST
        FILES = request.FILES
        form = forms.CronogramaForm(request.POST, request.FILES)
        file = FILES['crono']

        pd = pdfhandler.PDFhandler(file)
        pd.readFile2()
        pd.exportData()
        if pd.getSizeData() > 0:
            messages.success(request, 'PDF PROCESSADO COM SUCESSO')
            data = pd.getData()
            print_data = True
        else:
            messages.error(request, 'PDF NÃO CONTÉM DADOS OU É INVÁLIDO')

    return render(
        request,
        'destinations/pages/load_cronograma.html',
        context={'form': form, 'data': data, 'print_data': print_data}
    )


def saidas(request):  # View de rota para registro de saídas de produtos
    return render(
        request,
        "destinations/pages/registro-saidas.html",
        context={"saidas": [makeSaida() for _ in range(19)]},
    )


def registrodestino(request):  # View de rota para registro de doação
    return render(request, "destinations/pages/registro-destino.html")


def planilha(request):  # View de rota para planilha de produtos p/ doação
    return render(request, "destinations/pages/gerar-planilha.html")

destinations/templates/destinations/pages/entidades-insert.html
{% extends "destinations/global_templates/destinations-global.html" %}

{% block content %}

{% if messages %}
{% for msg in messages %}
  <div style="width: 63rem; margin: 2rem auto" class="message {{ msg.tags }}">
    {{ msg }}
  </div>
{% endfor %}
{% endif %}

<div class="div-form">
  <form action="" method="POST" autocomplete="off">
    {% csrf_token %}
    <div class="div-form-tit">
    ENTIDADES
  </div>
  <div class="div-form-content">

    {% for field in form %}
    {% if field.label != 'Ativo?' and field.label != 'Option' %}
    <div>
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
      {% if field.help_text %}
      <p class="help_text">
        {{ field.help_text }}
      </p>
      {% endif %}

      {% if field.errors%}
      <p class="error">
        {{ field.errors }}
      </p>
      {% endif %}
    </div>
    {% endif %}
    {% endfor %}

    <div>
      <div class="uppercase" style="height: 2rem;">
        {{ form.ativo.label }}
      </div>
      <div class="div-row-left">
        {% for opt in form.ativo %}
        <div class="div-row-left" style="align-items: end; width: 6rem;">
          <label for="{{ opt.id_for_label }}">{{ opt.choice_label }}</label>
          {{ opt.tag }}
        </div>
        {% endfor %}
      </div>
      <span class="help_text">
        {{ form.ativo.help_text }}
      </span>
    </div>
  </div>
  <div class="div-form-footer">
    <button type="submit">Salvar</button>&nbsp;&nbsp;
    <button type="reset">Cancelar</button>
  </div>
</div>
</form>
{% endblock content %}

destinations/templates/destinations/pages/entidades-update.html
{% extends "destinations/global_templates/destinations-global.html" %}

{% block content %}

{% if messages %}
{% for msg in messages %}
  <div style="width: 63rem; margin: 2rem auto" class="message {{ msg.tags }}">
    {{ msg }}
  </div>
{% endfor %}
{% endif %}

<div class="div-form">
  <form action="" method="POST" autocomplete="off">
    {% csrf_token %}
    <div class="div-form-tit">
    ATUALIZAÇÃO DE ENTIDADE
  </div>
  <div class="div-form-content">
    <div>
      <label for="{{ form.selectEntidade.id_for_label }}">{{ form.selectEntidade.label }}</label>
      <select name="selectEntidade" id="{{ form.selectEntidade.id_for_label }}">
        <option value="0">SELECIONE UMA ENTIDADE PARA ATUALIZAR</option>
        {% for option in options %}
        <option value="{{ option.id }}">{{ option.razao }}</option>
        {% endfor %}
      </select>
      <button type="button" id="btn-load">Carregar Dados</button>
    </div>
  </div>
  <div class="div-form-content">

    {% for field in form %}
    {% if field.label != 'Ativo?' and field.label != 'Cnpj' and field.label != 'Option' and field.label != 'Entidade' %}
    <div>
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
      {% if field.help_text %}
      <p class="help_text">
        {{ field.help_text }}
      </p>
      {% endif %}

      {% if field.errors%}
      <p class="error">
        {{ field.errors }}
      </p>
      {% endif %}
    </div>
    {% endif %}
    {% endfor %}

    <div>
      <div class="uppercase" style="height: 2rem;">
        {{ form.ativo.label }}
      </div>
      <div class="div-row-left">
        {% for opt in form.ativo %}
        <div class="div-row-left" style="align-items: end; width: 6rem;">
          <label for="{{ opt.id_for_label }}">{{ opt.choice_label }}</label>
          {{ opt.tag }}
        </div>
        {% endfor %}
      </div>
      <span class="help_text">
        {{ form.ativo.help_text }}
      </span>
    </div>
  </div>
  <div class="div-form-footer">
    <button type="button" id="btn-save">Salvar</button>&nbsp;&nbsp;
    <button type="reset">Cancelar</button>
    {{ form.option }}
  </div>
</div>
</form>
<script>
$(document).ready(function(){
  
  $("#btn-load").click(function(){
    $("#id_option").val("load");
    $("form").submit();
  })

  $("#btn-save").click(function(){
    $("#id_option").val("save");
    $("form").submit();
  })

});
</script>

{% endblock content %}

destinations/templates/destinations/pages/entidades.html
{% extends "destinations/global_templates/destinations-global.html" %}

{% block content %}

{% if messages %}
{% for msg in messages %}
  <div style="width: 63rem; margin: 2rem auto" class="message {{ msg.tags }}">
    {{ msg }}
  </div>
{% endfor %}
{% endif %}

<div class="div-form">
  <form action="" method="POST" autocomplete="off">
    {% csrf_token %}
    <div class="div-form-tit">
    ENTIDADES
  </div>
  <div class="div-form-content">

    {% for field in form %}
    {% if field.label != 'Ativo?' %}
    <div>
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
      {% if field.help_text %}
      <p class="help_text">
        {{ field.help_text }}
      </p>
      {% endif %}

      {% if field.errors%}
      <p class="error">
        {{ field.errors }}
      </p>
      {% endif %}
    </div>
    {% endif %}
    {% endfor %}

    <div>
      <div class="uppercase" style="height: 2rem;">
        {{ form.ativo.label }}
      </div>
      <div class="div-row-left">
        {% for opt in form.ativo %}
        <div class="div-row-left" style="align-items: end; width: 6rem;">
          <label for="{{ opt.id_for_label }}">{{ opt.choice_label }}</label>
          {{ opt.tag }}
        </div>
        {% endfor %}
      </div>
      <span class="help_text">
        {{ form.ativo.help_text }}
      </span>
    </div>
  </div>
  <div class="div-form-footer">
    <button type="submit">Salvar</button>&nbsp;&nbsp;
    <button type="reset">Cancelar</button>
  </div>
</div>
</form>
{% endblock content %}

destinations/templates/destinations/pages/gerar-planilha.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'destinations/css/style-main.css' %}">
  <link rel="stylesheet" href="{% static 'destinations/css/style-menus.css' %}">
  <link rel="stylesheet" href="{% static 'destinations/css/style-conteiners.css' %}">
  <link rel="stylesheet" href="{% static 'destinations/css/style-forms.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SIDPE - Sistema Integrado da Divisão de Pré-Embalados</title>
</head>

<body>

  <div class="grid-container">

    <header class="grid-header">
      <img class="logo" src="{% static 'destinations/img/logo_inmeq_inmetro.png' %}">
      <div class="container-header">SIDPE - Sistema Integrado da Divisão de Pré-Embalados</div>
    </header>

    <nav class="grid-nav" id="itens">
      <div id="metas" class="item-menu">METAS</div>
      <div id="dir" class="item-menu">DOAÇÃO/INUTILIZAÇÃO/RETIRADA</div>
      <div id="simulacoes" class="item-menu">SIMULAÇÕES</div>
      <div id="sair" class="item-menu">SAIR</div>
    </nav>

    <section class="grid-section" id="subitens">
      <div class="item-submenu" id="rdir">REGISTRAR DESTINO DE PRODUTOS</div>
      <div class="item-submenu" id="cnt">REGISTRAR DOAÇÃO</div>
      <div class="item-submenu" id="cnt">CADASTRO DE ENTIDADES</div>
      <div class="item-submenu" id="gpl">GERAR PLANILHA SGI</div>
      <div class="item-submenu" id="cnc">CANCELAR</div>
    </section>

    <main class="grid-main">

      <h2>GERAR PLANILHA (SGI)</h2>

      <div>
        <form autocomplete="off">

          <div class="div-output-block">

            <div style="display: flex; padding-bottom: 2rem;">
              <span>Período:&nbsp;&nbsp;&nbsp;&nbsp;</span>
              <input type="date" id="data1" style="width: 10rem;">&nbsp;&nbsp;&nbsp;&nbsp;
              <label for="data1">até:&nbsp;</label>
              <input type="date" id="data2" style="width: 10rem;">
            </div>

            <div style="display: flex; justify-content: center;">
              <button type="button" id="gerar" disabled>Gerar Planilha</button>&nbsp;&nbsp;&nbsp;&nbsp;
              <button type="button" id="cancelar">Cancelar</button>
            </div>
          </div>

        </form>
      </div>

    </main>

  </div>
</body>

</html>
<script>

  $(document).ready(function () {

    $("#dir").click(function () {

      $("#subitens").slideDown("slow");

    });

  })

</script>

destinations/templates/destinations/pages/index.html
{% extends "destinations/global_templates/destinations-global.html" %}

{% block content %}
{% if messages %}
  {% for msg in messages %}
    {{ msg }}
  {% endfor %}
{% endif %}
{% endblock content %}

destinations/templates/destinations/pages/load_cronograma.html
{% extends "destinations/global_templates/destinations-global.html" %}

{% block content %}

{% if messages %}
{% for msg in messages %}
<div class="message {{ msg.tags }}" style='width: 63rem; margin: 2rem auto'>
  {{msg}}
</div>
{% endfor %}
{% endif %}

<div class="div-form">
  <form action="" method='POST' enctype="multipart/form-data">
  {% csrf_token %}
    <div class="div-form-tit">
      CARREGAR CRONOGRAMA DE PERÍCIAS
    </div>
    <div class="div-form-content" style="display: flex; flex-direction: row">
      {{ form.crono }}
      {{ form.option }}
      &nbsp;&nbsp;
      <button type="submit">PDF</button>
    </div>
    {% if print_data %}
    <div class="div-form-tit">
      LANÇAMENTO SELECIONADO
    </div>
    <div class="dv-form-content">
      Campos para edição de lançamentos aqui
    </div>
    <div class="div-form-tit">
      LANÇAMENTOS
    </div>
    <div class="div-form-content" style="background-color: #e6e6e6; padding: 0.5rem 0.8rem">
      <div class="grid-saidas" >
        <div>DATA</div>
        <div>TC</div>
        <div>PRODUTO</div>
        <div>MARCA</div>
        <div>CONT. NOM.</div>
        <div>QUANT.</div>
        <div>TIPO SAÍDA</div>
      </div>
    </div>
    <div style="overflow-y: auto; max-height: 40rem">
      {% for dt in data %}
      <div class="div-form-content">
        <div class="grid-saidas">
          <div>{{dt.data}}</div>
          <div>{{ dt.tc }}</div>
          <div>{{ dt.produto }}</div>
          <div>{{ dt.marca }}</div>
          <div>{{ dt.qn }}</div>
          <div>{{ dt.qt }}</div>
          <div>{{ dt.tipo_saida }}</div>
        </div>
      </div>
      {% endfor %}
    </div>
      {% endif %}
  </form>
</div>
  
{% endblock content %}}

destinations/templates/destinations/pages/registro-destino.html
{% include "destinations/partials/head.html" %}

    <main class="grid-main">



    </main>

{% include "destinations/partials/footer.html" %}

destinations/templates/destinations/pages/registro-saidas.html
{% extends "destinations/global_templates/destinations-global.html" %}
{% block content %}
<div class="div-form" style="width: 90rem">
  <form autocomplete="off">
    <div class="div-form-tit">
      REGISTRO DE SAÍDAS DIÁRIAS
    </div>
    <div class="div-form-footer">
      <input type="file" name="file" accept="application/pdf" id="file">&nbsp;
      <div class="div-flex-row">
        <button type="button" id="carregar_dados" disabled>Carregar Dados</button>&nbsp;
        <button type="button" id="cancelar">Cancelar</button>&nbsp;
      </div>
    </div>
    <div class="div-col-left" style="overflow-y: auto; padding-left: 1rem">
      <div class="grid-saidas">
        <div>DATA</div>
        <div>TC</div>
        <div>DESTINO</div>
        <div>PRODUTO</div>
        <div>MARCA</div>
        <div>QN</div>
        <div>QUANT</div>
      </div>
      <div class="grid-saidas" style="overflow-y: auto;">

        {% for saida in saidas %}
        <div>
          <input type="date" name="data[]" id="data[]" style="width: 9.4rem" value="{{saida.data}}">
        </div>
        <div>
          <input type="text" name="tc[]" id="tc[]" style="width: 5.2rem;" value="{{saida.tc}}">
        </div>
        <div>
          <select name="destino[]" id="destino[]" style="width: 9rem;">
            <option value=""></option>
            {% if saida.destino == 'd' %}
            <option value="d" selected>Doação</option>
            {% else %}
            <option value="d">Doação</option>
            {% endif %}
            {% if saida.destino == 'i' %}
            <option value="i" selected>Inutilização</option>
            {% else %}
            <option value="i">Inutilização</option>
            {% endif %}
            {% if saida.destino == 'r'%}
            <option value="r" selected>Retirada</option>
            {% else %}
            <option value="r">Retirada</option>
            {% endif %}
          </select>
        </div>
        <div>
          <input type="text" name="produto[]" id="produto[]" style="width: 27.2rem" value="{{saida.produto}}">
        </div>
        <div>
          <input type="text" name="marca[]" id="marca[]" size="12rem" value="{{saida.marca}}">
        </div>
        <div>
          <input type="text" name="qn[]" id="qn[]" size="4rem" style="width: 4rem;" value="{{saida.qn}}">
        </div>
        <div>
          <input type="text" name="quant[]" id="quant[]" size="2rem" value="{{saida.quant}}">&nbsp;
          <button type="button" id="excluir[]" disabled
            style="display: flex; align-items: center; width: 5rem; height: 2rem;">
            <i class="fa-solid fa-trash-can"></i>
          </button>
        </div>

        {% endfor %}

      </div>
    </div>
    <div class="div-form-footer">
      &nbsp;
    </div>
    <input type="hidden" name="option" id="option" value="">
  </form>
</div>
{% endblock content %}